# Generated by Django 5.2.8 on 2025-11-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='manufacturing',
            field=models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo visualizar'), (2, 'Leer y escribir')], default=0),
        ),
    ]
