# Generated by Django 5.2.8 on 2025-11-15 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='suppliers.paymentmethod', verbose_name='Payment Method'),
        ),
    ]
