# Generated by Django 5.2.8 on 2025-11-15 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0002_materialtype_unit_remove_material_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='materials.materialtype'),
        ),
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='materials.unit'),
        ),
    ]
