# Generated by Django 5.2.8 on 2025-11-16 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_currency'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='currency_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
    ]
