# Generated by Django 5.2.8 on 2025-11-19 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymovement_movement_date_and_more'),
        ('purchases', '0002_alter_purchaseorderline_currency_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.inventorylocation'),
        ),
    ]
