# Generated by Django 5.2.8 on 2025-11-23 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id_snapshot', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('report_type', models.CharField(choices=[('MONTHLY_SUMMARY', 'Resumen Mensual'), ('SALES_REPORT', 'Reporte de Ventas'), ('PURCHASE_REPORT', 'Reporte de Compras'), ('INVENTORY_REPORT', 'Reporte de Inventario'), ('PRODUCTION_REPORT', 'Reporte de Producción'), ('ACCOUNTING_REPORT', 'Reporte Contable')], max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sales', models.IntegerField(default=0)),
                ('total_purchases', models.IntegerField(default=0)),
                ('total_production_orders', models.IntegerField(default=0)),
                ('inventory_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instantánea de Reporte',
                'verbose_name_plural': 'Instantáneas de Reportes',
                'db_table': 'report_snapshot',
                'ordering': ['-period_end', '-created_at'],
                'indexes': [models.Index(fields=['report_type', 'period_start', 'period_end'], name='report_snap_report__d910e1_idx')],
            },
        ),
    ]
