# Generated by Django 5.2.8 on 2025-11-18 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='movement_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
