# Generated by Django 5.2.8 on 2025-11-19 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0003_material_material_type_material_status_material_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bill_of_materials', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material')),
            ],
            options={
                'verbose_name': 'Bill of Materials',
                'verbose_name_plural': 'Bills of Materials',
                'db_table': 'bill_of_materials',
                'ordering': ['material'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialsLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bill_of_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='manufacturing.billofmaterials')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material')),
                ('unit_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.unit')),
            ],
            options={
                'verbose_name': 'Bill of Materials Line',
                'verbose_name_plural': 'Bill of Materials Lines',
                'db_table': 'lines_bill_of_materials',
                'ordering': ['bill_of_materials', 'component'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Order Status',
                'verbose_name_plural': 'Work Order Statuses',
                'db_table': 'work_order_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_work_order', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_of_materials', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.billofmaterials')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufacturing.workorderstatus')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'db_table': 'work_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
