# Generated by Django 5.2.8 on 2025-11-19 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorymovement_movement_date_and_more'),
        ('manufacturing', '0002_alter_workorderstatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_destination', to='inventory.inventorylocation'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='origin_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_origin', to='inventory.inventorylocation'),
        ),
    ]
