# Generated by Django 5.2.8 on 2025-11-15 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_customer', models.CharField(max_length=50, unique=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('tax_id', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('zip_code', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_role', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
