# Generated by Django 5.2.8 on 2025-11-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payment_method',
        ),
    ]
