# Generated by Django 5.2.8 on 2025-11-15 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_payment_method'),
        ('suppliers', '0003_add_payment_method_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='suppliers.paymentmethod', verbose_name='Payment Method'),
        ),
    ]
