# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountnature',
            name='id_account_nature',
            field=models.CharField(default='AN001', max_length=50, unique=True, verbose_name='Account Nature ID'),
        ),
        migrations.AlterField(
            model_name='accountnature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, editable=False),
        ),
        migrations.AlterField(
            model_name='accountnature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, editable=False),
        ),
    ]
