# Generated by Django 5.2.8 on 2025-11-16 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountnature_id_account_nature'),
        ('core', '0002_country_currency'),
        ('purchases', '0002_alter_purchaseorderline_currency_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountaccount',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.country'),
        ),
        migrations.AlterField(
            model_name='accountaccount',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
