# Generated by Django 5.2.8 on 2025-11-20 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_accountaccount_country_and_more'),
        ('core', '0002_country_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_journal_entry', models.CharField(help_text='Identificador único del asiento contable (ej: JE-000001)', max_length=50, unique=True, verbose_name='Journal Entry ID')),
                ('date', models.DateField(help_text='Fecha del asiento contable', verbose_name='Fecha')),
                ('description', models.TextField(help_text='Descripción general del asiento contable', verbose_name='Descripción')),
                ('operation_type', models.CharField(choices=[('PURCHASE', 'Compra'), ('SALE', 'Venta'), ('PRODUCTION', 'Producción'), ('ADJUSTMENT', 'Ajuste de Inventario'), ('TRANSFER', 'Transferencia'), ('MANUAL', 'Manual')], help_text='Tipo de operación que genera el asiento', max_length=50, verbose_name='Tipo de Operación')),
                ('reference', models.CharField(help_text='ID del documento origen (ej: PO-0001, SO-0001, WO-0001, etc.)', max_length=100, verbose_name='Referencia')),
                ('module', models.CharField(choices=[('PURCHASES', 'Compras'), ('SALES', 'Ventas'), ('MANUFACTURING', 'Manufactura'), ('INVENTORY', 'Inventario'), ('ACCOUNTING', 'Contabilidad')], help_text='Módulo del sistema que genera el asiento', max_length=50, verbose_name='Módulo')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('POSTED', 'Contabilizado'), ('CANCELLED', 'Anulado')], default='DRAFT', help_text='Estado del asiento contable', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('currency', models.ForeignKey(help_text='Moneda del asiento contable', on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='core.currency', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'db_table': 'journal_entry',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Descripción específica de esta línea (opcional)', max_length=500, verbose_name='Descripción')),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Monto del débito', max_digits=15, verbose_name='Débito')),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Monto del crédito', max_digits=15, verbose_name='Crédito')),
                ('position', models.IntegerField(help_text='Orden de la línea en el asiento', verbose_name='Posición')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('account', models.ForeignKey(help_text='Cuenta contable afectada', on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='accounting.accountaccount', verbose_name='Cuenta')),
                ('journal_entry', models.ForeignKey(help_text='Asiento contable al que pertenece esta línea', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='Asiento Contable')),
            ],
            options={
                'verbose_name': 'Línea de Asiento Contable',
                'verbose_name_plural': 'Líneas de Asiento Contable',
                'db_table': 'journal_entry_line',
                'ordering': ['journal_entry', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['id_journal_entry'], name='journal_ent_id_jour_647ace_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='journal_ent_date_a963b2_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['operation_type'], name='journal_ent_operati_b7e378_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['module'], name='journal_ent_module_b3ff7a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference'], name='journal_ent_referen_9692ac_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['-created_at'], name='journal_ent_created_b30f09_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['journal_entry'], name='journal_ent_journal_0d484e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account'], name='journal_ent_account_4ccec9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentryline',
            unique_together={('journal_entry', 'position')},
        ),
    ]
