# Generated by Django 5.2.8 on 2025-11-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_journalentry_journalentryline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo actual de la cuenta (actualizado automáticamente al contabilizar asientos)', max_digits=14, verbose_name='Saldo Actual'),
        ),
    ]
