# Generated by Django 5.2.8 on 2025-11-19 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_country_currency'),
        ('customers', '0003_customer_payment_method'),
        ('inventory', '0002_inventorymovement_movement_date_and_more'),
        ('materials', '0003_material_material_type_material_status_material_unit'),
        ('purchases', '0003_purchaseorder_destination_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sales_order', models.CharField(help_text='Identificador único de la orden de venta (ej: SO-0001)', max_length=50, unique=True, verbose_name='Sales Order ID')),
                ('issue_date', models.DateField(help_text='Fecha de emisión de la orden de venta', verbose_name='Issue Date')),
                ('notes', models.TextField(blank=True, help_text='Notas o comentarios adicionales sobre la orden', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(help_text='Cliente al que se le vende', on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='customers.customer', verbose_name='Customer')),
                ('source_location', models.ForeignKey(blank=True, help_text='Ubicación de inventario desde donde se despacha la orden', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='inventory.inventorylocation', verbose_name='Source Location')),
                ('status', models.ForeignKey(help_text='Estado actual de la orden de venta', on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='purchases.orderstatus', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'db_table': 'sales_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sales_order_line', models.CharField(help_text='Identificador único de la línea (ej: SO-0001-L001)', max_length=50, unique=True, verbose_name='Sales Order Line ID')),
                ('position', models.IntegerField(help_text='Número de posición o secuencia de la línea en la orden', verbose_name='Position')),
                ('quantity', models.IntegerField(help_text='Cantidad vendida del material', verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio unitario de venta', max_digits=10, verbose_name='Unit Price')),
                ('delivered_quantity', models.IntegerField(default=0, help_text='Cantidad ya entregada del material', verbose_name='Delivered Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_order_lines', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('currency_customer', models.ForeignKey(help_text='Moneda del precio de venta', on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='core.currency', verbose_name='Currency')),
                ('material', models.ForeignKey(help_text='Material o producto vendido', on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='materials.material', verbose_name='Material')),
                ('sales_order', models.ForeignKey(help_text='Orden de venta a la que pertenece esta línea', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder', verbose_name='Sales Order')),
                ('unit_material', models.ForeignKey(help_text='Unidad de medida del material', on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='materials.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Sales Order Line',
                'verbose_name_plural': 'Sales Order Lines',
                'db_table': 'lines_sales_order',
                'ordering': ['sales_order', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['id_sales_order'], name='sales_order_id_sale_fada25_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer'], name='sales_order_custome_62a3d7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='sales_order_status__1eaf37_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['-created_at'], name='sales_order_created_03194e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderline',
            index=models.Index(fields=['id_sales_order_line'], name='lines_sales_id_sale_fa2ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderline',
            index=models.Index(fields=['sales_order'], name='lines_sales_sales_o_2c8221_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderline',
            index=models.Index(fields=['material'], name='lines_sales_materia_62edf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesorderline',
            unique_together={('sales_order', 'position')},
        ),
    ]
