# Generated by Django 5.2.8 on 2025-11-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Número de factura o referencia contable asociada (integración contable)', max_length=50, null=True, verbose_name='Invoice Number'),
        ),
    ]
